# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Topdeck < Formula
  desc "A beautiful terminal presentation tool"
  homepage "https://github.com/alexcabrera/topdeck"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexcabrera/topdeck/releases/download/v0.1.0/topdeck_0.1.0_darwin_amd64.tar.gz"
      sha256 "9844c2f6636f7f4092a6690c8d6f7f9c973dd74ecd4ff73138d8b92f1a37480e"

      def install
        bin.install "topdeck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexcabrera/topdeck/releases/download/v0.1.0/topdeck_0.1.0_darwin_arm64.tar.gz"
      sha256 "013da2f29444e66f4e4a6542f8fc09f820ae4d700fa3aa240a662560b068b9e2"

      def install
        bin.install "topdeck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexcabrera/topdeck/releases/download/v0.1.0/topdeck_0.1.0_linux_amd64.tar.gz"
      sha256 "ab9c3d77efd1e653a6cb834f4cb60d1bec58f003d6c6d6ba57b95e0c3567e091"
      def install
        bin.install "topdeck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexcabrera/topdeck/releases/download/v0.1.0/topdeck_0.1.0_linux_arm64.tar.gz"
      sha256 "7f0a568513e8ed78b8b60764b20fcbe9ff9cb734604b46840f9d635eb87c22c0"
      def install
        bin.install "topdeck"
      end
    end
  end
end
